### ISSUE TITLE
Q: What if I have some stuff installed already?

### ISSUE THREAD

**Issue by miguelpaz** [Aerolab/setup#3]
What should I do? Qué hago?

PS: This is a great idea. Esto es Alta Idea de Aerolab.

**Comment by RobertoGonzalez** [comment]
@miguelpaz El script lo usamos para inicializar Macs nuevas (o después de un factory reset), así que no lo testeamos en ese caso. Igualmente, a menos que lo hayan cambiado, Brew te sobreescribe el soft que tengas instalado y es raro que cause issues (y si lo va a hacer generalmente te avisa).

Si tenés ganas de probarlo en una Mac ya configurada hacé un backup por las dudas y correlo con no a todas las opciones. A lo sumo te dejará la Mac con Homebrew instalado y un montón de plugins de Quicklook.

Saludos!

**Comment by miguelpaz** [comment]
Gracias @RobertoGonzalez.
